const techs: Record<string, string> = {
  ts: "TypeScript",
  js: "JavaScript",
  mongo: "MongoDB",
  html: "HTML",
  css: "CSS",
  scss: "SCSS",
  node: "Node.js",
  vscode: "VSCode",
  figma: "Figma",
  git: "Git",
  github: "GitHub",
  react: "React",
  express: "Express",
  vue: "VueJS",
  nuxt: "NuxtJS",
  laravel: "Laravel",
  nest: "NestJS",
  tailwind: "Tailwind CSS",
  bootstrap: "Bootstrap",
  mysql: "MySQL",
  postgresql: "PostgreSQL",
  php: "PHP",
  docker: "Docker",
  linux: "Linux",
  nginx: "Nginx",
  "github-action": "GitHub Actions",
  cardano: "Cardano",
  sass: "SASS",
  webpack: "Webpack",
  next: "Next.js",
  zod: "Zod",
  python: "Python",
  flask: "Flask",
  ejs: "EJS",
};

export default techs;
